Написал первые настройки для компонентов экрана приветсвия и App и по…
htmlacademy-react/892619-guess-melody-5 pull request #2
Opened 2020-09-29 19:47 UTC by Egrik-Dev

…пробовал передать пропсы

2020-09-29 20:25 UTC, chechenev requested changes
Всё абсолютно правильно, я лишь хочу обратить внимание на стиль кода :)

2020-09-29 20:25 UTC, chechenev commented on src/components/app/app.jsx
> +      errorsCount = {errorsCount}
Всё верно, но советую взять в привычку не использовать пробелы вокруг `=`, потому что обычно такой стиль не используют. И лучше сразу привыкнуть писать правильнее и удобнее, чем потом переделывать все знаки равно

2020-09-29 20:25 UTC, chechenev commented on src/index.js
> +      errorsCount = {StartSettings.ERRORS_CONUNT}
Тоже самое и здесь :)

2020-09-30 02:57 UTC, Egrik-Dev commented on src/components/app/app.jsx
> +      errorsCount = {errorsCount}
Понял.
Спасибо, сейчас поправлю)

2020-09-30 07:17 UTC, merged